version: '1'

services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "8080:8080"

  mysql:
    build:
      context: ./db
    container_name: mon_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: flirtopia
    ports:
      - "3306:3306"

  node_app:
    build:
      context: ./backend
    container_name: mon_node_app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - ./test.sh:/test.sh
      - ./coordsCity.json:/app/coordsCity.json
      - ./manFirstName.json:/app/manFirstName.json
      - ./womanFirstName.json:/app/womanFirstName.json
      - ./scriptUsers.js:/app/scriptUsers.js
    command: ["/test.sh", "mon_mysql:3306", "--", "node", "dist/index.js"]
