"use strict";
exports.__esModule = true;
var express_1 = require("express");
var login_1 = require("../controllers/login");
var acceptJsonOnly_1 = require("../middlewares/acceptJsonOnly");
var router = express_1["default"].Router();
router.post('/signin', acceptJsonOnly_1["default"], login_1.signin);
router.post('/signup', acceptJsonOnly_1["default"], login_1.signup);
router.post('/resetPasword', login_1.resetPassword);
router.get('/token', login_1.checkToken);
router.get('/verifyToken', login_1.verifyTokenEmail);
router.get('/sendEmailResetPassword', login_1.sendEmailResetPassword);
exports["default"] = router;
